// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("CSharpExamples")]
[assembly: AssemblyProductAttribute("Intro_To_FP")]
[assembly: AssemblyDescriptionAttribute("Intro_To_FP")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
    }
}
